/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/injection`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Info`; params?: Router.UnknownInputParams; } | { pathname: `/components/LogsTable`; params?: Router.UnknownInputParams; } | { pathname: `/components/Navbar`; params?: Router.UnknownInputParams; } | { pathname: `/components/NextInjection`; params?: Router.UnknownInputParams; } | { pathname: `/utils/dateUtils`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/injection`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Info`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LogsTable`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Navbar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NextInjection`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/dateUtils`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/injection${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Info${`?${string}` | `#${string}` | ''}` | `/components/LogsTable${`?${string}` | `#${string}` | ''}` | `/components/Navbar${`?${string}` | `#${string}` | ''}` | `/components/NextInjection${`?${string}` | `#${string}` | ''}` | `/utils/dateUtils${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/injection`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Info`; params?: Router.UnknownInputParams; } | { pathname: `/components/LogsTable`; params?: Router.UnknownInputParams; } | { pathname: `/components/Navbar`; params?: Router.UnknownInputParams; } | { pathname: `/components/NextInjection`; params?: Router.UnknownInputParams; } | { pathname: `/utils/dateUtils`; params?: Router.UnknownInputParams; };
    }
  }
}
